# 非 host 版本, 不使用本机代理
version: '3.8'
services:
  antsk:
    container_name: antsk
    image: registry.cn-hangzhou.aliyuncs.com/xuzeyu91/antsk:v0.6.4
    # 如果需要pytorch环境需要使用下面这个镜像，镜像比较大
    # image: registry.cn-hangzhou.aliyuncs.com/xuzeyu91/antsk:p0.6.4
    ports:
      - 5000:5000
    networks:
      - antsk
    restart: always
    environment:
      - ASPNETCORE_URLS=http://*:5000
    volumes:
      - ./appsettings.json:/app/appsettings.json # 本地配置文件 需要放在同级目录
      - /AntSK/model:/app/model
      - /AntSK/model:/root/.cache/modelscope/hub/AI-ModelScope # LLamaFactory模型文件
networks:
  antsk:
